[build]
base = "/"
command = "pnpm -F @proj-airi/vad-asr-chat-tts run build"
publish = "/apps/vad-asr-chat-tts/dist"

[build.environment]
NODE_VERSION = "23"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = false
